name: CI Pipelines 1

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [ready_for_review]

env:
  HAS_FRONTEND_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'frontend') || contains(github.event.issue.labels.*.name, 'frontend') }}
  TRIGGER_BY_APPROVAL: ${{ github.event.review.state == 'approved' }}
  TRIGGER_BY_COMMENT: ${{ github.event.comment.body == 'run-ci' }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: CI Pipelines 2
    steps:
      - uses: actions/checkout@v2
      - name: Display Event
        run: echo "${{ toJSON(github.event) }}"
      - name: ECO HAS_FRONTEND_LABEL
        run: echo "${{ env.HAS_FRONTEND_LABEL }}"
      - name: ECO TRIGGER_BY_APPROVAL
        run: echo "${{ env.TRIGGER_BY_APPROVAL }}"
      - name: ECO TRIGGER_BY_COMMENT
        run: echo "${{ env.TRIGGER_BY_COMMENT }}"
