name: CI Pipelines 1

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [ready_for_review]
  pull_request_review_comment:
    types: [created]

env:
  HAS_FRONTEND_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'frontend') || contains(github.event.issue.labels.*.name, 'frontend') }}
  TRIGGER_BY_APPROVAL: ${{ github.event.review.state == 'approved' }}
  TRIGGER_BY_COMMENT: ${{ github.event.comment.body == 'run-ci' }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: CI Pipelines 2
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Cache
        uses: actions/cache@v3
        id: frontend_node_modules_cache
        env:
          cache-name: fe-cache-node_modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - if: ${{ steps.frontend_node_modules_cache.outputs.cache-hit != 'true' }}
        name: Install Front End Dependencies
        run: npm ci
      