name: CI Pipelines

on:
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: CI Pipelines
    steps:
      - uses: actions/checkout@v2
      - name: Display Event
        run: echo "${{ github.event.pull_request }}"
