name: CI Pipelines

on:
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: CI Pipelines
    steps:
      - uses: actions/checkout@v2
      - name: Display Event
        run: echo "${{ github.event.action }}" "${{ toJSON(github.event.pull_request) }}"
